### ISSUE TITLE
Improve error message when passing multiple labels

### ISSUE THREAD

**Issue by bkchr** [chevdor/ruled_labels#11]
https://github.com/paritytech/cumulus/actions/runs/3920282594/jobs/6733728041

The issue here was that the user passed 2 T labels, while it only expected one T label. 

> Release mentions need a topic (T) | Since you have one of the B1 label(s), you need to include one of the T* label(s)

Instead of this it should reported something like "Multiple T* labels detected, only one expected".

**Comment by chevdor** [comment]
The issue here is that [the rule](https://github.com/paritytech/labels/blob/main/ruled_labels/specs_cumulus.yaml#L216-L221) is a little too tight and allows 1 `T`(opic) label only.

The message matches the rule that says:
> If there is B1, you must provide ***ONE*** T label 

This rule is not what we want as `one` does not mean **one or more** but **one and only one**.
I don't think there is anything wrong when users pass mutliple `T` labels in a PR, this is actually a good thing. 

The `T` labels are not exclusive so the rule should be:
> if there is `B1`, you must provide ***SOME*** T labels" (1 or more)

That would then allow the the case you linked where 2 `T` labels are provided.

I created [a PR](https://github.com/paritytech/labels/pull/4) relaxing this rule and added a test with mutiple T labels, ensuring this case passes.
